# Generated by Django 6.0.3 on 2026-08-08 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['is_public'], name='wishlists_w_is_publ_cba7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user'], name='wishlists_w_user_id_0737aa_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['session_id'], name='wishlists_w_session_c1dd5d_idx'),
        ),
    ]
