# Generated by Django 6.0.3 on 2026-08-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_phone_number_orderaddress'),
        ('payments', '0002_alter_payment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('CAD', 'CAD - Canadian Dollar'), ('JPY', 'JPY - Japanese Yen'), ('NGN', 'NGN - Nigerian Naira'), ('GHS', 'GHS - Ghanaian Cedi'), ('KES', 'KES - Kenyan Shilling'), ('ZAR', 'ZAR - South African Rand'), ('TZS', 'TZS - Tanzanian Shilling'), ('UGX', 'UGX - Ugandan Shilling'), ('RWF', 'RWF - Rwandan Franc'), ('XAF', 'XAF - Central African CFA Franc'), ('XOF', 'XOF - West African CFA Franc')], default='NGN', max_length=3),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference_id'], name='payments_pa_referen_7b9331_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_pa_created_b8a300_idx'),
        ),
    ]
